### ISSUE TITLE
Brak przykładu działania

### ISSUE THREAD

**Issue by Jaom** [emkael/jfrteamy-vcards#1]
A w każdym razie przeykład działania mnie nie działa:
https://github.com/emkael/jfrteamy-vcards#przyk%C5%82ad-dzia%C5%82ania

**Comment by Jaom** [comment]
Dlaczego w przykładzie działania jest A.gif pod zawodnikami drużyny?

**Comment by emkael** [comment]
![vcards](https://user-images.githubusercontent.com/3368944/38745025-b8ffaf76-3f43-11e8-8458-3130953b18ac.gif)

Nie rozumiem pytania (i jego związku z poprawką w README).
